# -*- coding: utf-8 -*-
"""Casos de uso por industria, historias de éxito y programa de afiliados (ES / EN).

Cada historia es (lugar_es, lugar_en, texto_es, texto_en).
"""

# ---------------------------------------------------------------- Industrias
INDUSTRIAS = [
    {
        'id': 'alquiler', 'ico': 'coche',
        'nombre': ('Alquiler de vehículos', 'Vehicle rental'),
        'necesidad': ('Evitar devoluciones tardías, saber dónde está cada coche', 'Avoid late returns and know where every car is'),
        'soluciones': ['solucion-flotas'],
        'historias': [
            ('Puerto del Rosario, Fuerteventura', 'Puerto del Rosario, Fuerteventura',
             'Javier gestiona 8 coches de alquiler y localiza uno que un cliente dejó fuera de la zona permitida, antes de que llame la aseguradora.',
             'Javier runs 8 rental cars and locates one a customer left outside the permitted area, before the insurer calls.'),
            ('Playa Blanca, Lanzarote', 'Playa Blanca, Lanzarote',
             'Beatriz recupera un coche de alquiler abandonado en un descampado tras un cliente que no lo devolvió.',
             'Beatriz recovers a rental car abandoned on waste ground after a customer failed to return it.'),
            ('Adeje, Tenerife', 'Adeje, Tenerife',
             'El rentacar de Fran evita una reclamación al detectar a tiempo un trayecto no autorizado a otra isla.',
             'Fran’s car hire business avoids a claim by spotting an unauthorised trip to another island in time.'),
            ('Las Palmas de Gran Canaria', 'Las Palmas de Gran Canaria',
             'La empresa de Diego ve que un coche sigue parado en el aeropuerto tras la hora de entrega y avisa al cliente antes de aplicar un recargo.',
             'Diego’s company sees that a car is still parked at the airport after the return time and warns the customer before charging a surcharge.'),
            ('San Sebastián de La Gomera', 'San Sebastián de La Gomera',
             'Marisa detecta que un vehículo de su flota de alquiler ha salido de la isla en ferry sin autorización.',
             'Marisa spots that a vehicle from her rental fleet has left the island by ferry without authorisation.'),
            ('Santa Cruz de La Palma', 'Santa Cruz de La Palma',
             'El rentacar familiar de los Delgado reduce las llamadas de «¿dónde está mi coche?» desde que usan Canary GPS.',
             'The Delgado family’s car hire business gets far fewer “where’s my car?” calls since they started using Canary GPS.'),
        ],
    },
    {
        'id': 'tours', 'ico': 'mapa',
        'nombre': ('Tours y excursiones turísticas', 'Tours and excursions'),
        'necesidad': ('Verificar recorridos, publicidad en movimiento a patrocinadores', 'Check routes, offer advertising on the move to sponsors'),
        'soluciones': ['solucion-flotas', 'solucion-publicidad-en-movimiento'],
        'historias': [
            ('Vilaflor, Tenerife', 'Vilaflor, Tenerife',
             'El guía Andrés confirma que su jeep sigue el recorrido previsto por el Teide sin desviarse del circuito autorizado.',
             'Guide Andrés confirms that his jeep follows the planned route around Mount Teide without leaving the authorised circuit.'),
            ('Maspalomas, Gran Canaria', 'Maspalomas, Gran Canaria',
             'La empresa de tours de Noelia reparte mejor el mantenimiento viendo cuántos kilómetros hace cada vehículo al mes.',
             'Noelia’s tour company plans maintenance better by seeing how many kilometres each vehicle covers a month.'),
            ('Corralejo, Fuerteventura', 'Corralejo, Fuerteventura',
             'El capitán Rubén localiza su embarcación de excursiones tras un amarre suelto durante la noche.',
             'Captain Rubén locates his excursion boat after a mooring came loose during the night.'),
            ('Haría, Lanzarote', 'Haría, Lanzarote',
             'Los tours en buggy de Cristina optimizan las rutas viendo qué tramos se repiten más.',
             'Cristina’s buggy tours improve their routes by seeing which stretches are repeated most.'),
            ('Valle Gran Rey, La Gomera', 'Valle Gran Rey, La Gomera',
             'Las excursiones de senderismo de Iván detectan un vehículo de apoyo detenido más tiempo del normal y llaman para comprobar que todo iba bien.',
             'Iván’s hiking excursions notice a support vehicle stopped for longer than usual and call to check everything is fine.'),
            ('Los Llanos de Aridane, La Palma', 'Los Llanos de Aridane, La Palma',
             'Las rutas guiadas por la Ruta de los Volcanes de Patricia usan el historial de recorridos para diseñar una ruta nueva más atractiva.',
             'Patricia’s guided tours along the Volcano Route use the route history to design a new, more attractive itinerary.'),
        ],
    },
    {
        'id': 'reparto', 'ico': 'camion',
        'nombre': ('Reparto y logística', 'Delivery and logistics'),
        'necesidad': ('Tiempos de ruta reales, no estimados', 'Real route times, not estimates'),
        'soluciones': ['solucion-flotas'],
        'historias': [
            ('Telde, Gran Canaria', 'Telde, Gran Canaria',
             'El repartidor Óscar demuestra a un cliente que la entrega llegó a la hora exacta gracias al registro de ruta.',
             'Delivery driver Óscar proves to a customer that the delivery arrived exactly on time thanks to the route log.'),
            ('Arrecife, Lanzarote', 'Arrecife, Lanzarote',
             'La empresa de paquetería de Vanesa detecta una furgoneta parada más de lo normal y evita un retraso en cadena.',
             'Vanesa’s parcel company spots a van stopped for longer than usual and avoids a knock-on delay.'),
            ('Puerto del Rosario, Fuerteventura', 'Puerto del Rosario, Fuerteventura',
             'El reparto de bebidas de Kevin optimiza rutas viendo qué trayectos se repiten cada semana.',
             'Kevin’s drinks distribution business optimises its routes by seeing which journeys are repeated every week.'),
            ('Candelaria, Tenerife', 'Candelaria, Tenerife',
             'La logística de Sonia identifica un desvío no autorizado de un conductor subcontratado.',
             'Sonia’s logistics firm identifies an unauthorised detour by a subcontracted driver.'),
            ('Valverde, El Hierro', 'Valverde, El Hierro',
             'El reparto de suministros de Isabel llega siempre a tiempo pese a lo aislado de algunas zonas de la isla.',
             'Isabel’s supply deliveries always arrive on time despite how isolated some parts of the island are.'),
            ('El Paso, La Palma', 'El Paso, La Palma',
             'La mensajería de Alberto reduce quejas de clientes al poder informar la ubicación exacta del pedido.',
             'Alberto’s courier service gets fewer complaints because it can tell customers exactly where their order is.'),
        ],
    },
    {
        'id': 'obra', 'ico': 'casco',
        'nombre': ('Construcción y obra', 'Construction'),
        'necesidad': ('Seguridad en casetas y almacenes sin electricidad fija', 'Security for site huts and stores without a fixed power supply'),
        'soluciones': ['solucion-hogar-y-negocio'],
        'historias': [
            ('Agüimes, Gran Canaria', 'Agüimes, Gran Canaria',
             'La constructora de Raúl protege las herramientas de una caseta de obra sin electricidad conectada.',
             'Raúl’s building firm protects the tools in a site hut with no electricity connected.'),
            ('Tinajo, Lanzarote', 'Tinajo, Lanzarote',
             'La obra de Marta recibe un aviso de movimiento en un almacén de materiales durante un fin de semana.',
             'Marta’s building site gets a movement alert from a materials store over a weekend.'),
            ('Antigua, Fuerteventura', 'Antigua, Fuerteventura',
             'La cuadrilla de Julio localiza una furgoneta de herramientas en menos de una hora tras su desaparición.',
             'Julio’s crew locates a tool van less than an hour after it went missing.'),
            ('Frontera, El Hierro', 'Frontera, El Hierro',
             'La constructora familiar de los Pérez protege un generador eléctrico en una obra aislada.',
             'The Pérez family building firm protects a generator on an isolated site.'),
            ('Vallehermoso, La Gomera', 'Vallehermoso, La Gomera',
             'La contratista Yolanda detecta un intento de acceso a una caseta fuera del horario laboral.',
             'Contractor Yolanda detects an attempt to get into a site hut outside working hours.'),
            ('Fuencaliente, La Palma', 'Fuencaliente, La Palma',
             'La obra cerca del volcán de Sergio confía en el GPS porque ni siquiera hay cobertura de wifi en la zona.',
             'Sergio’s site near the volcano relies on the GPS because there is not even wifi coverage in the area.'),
        ],
    },
    {
        'id': 'hosteleria', 'ico': 'tienda',
        'nombre': ('Hostelería y locales comerciales', 'Hospitality and shops'),
        'necesidad': ('Aviso de intrusión fuera de horario', 'Intrusion alerts outside opening hours'),
        'soluciones': ['solucion-hogar-y-negocio'],
        'historias': [
            ('Puerto de la Cruz, Tenerife', 'Puerto de la Cruz, Tenerife',
             'El bar de Carmen recibe un aviso de apertura de la persiana en plena noche.',
             'Carmen’s bar gets an alert that the shutter has been opened in the middle of the night.'),
            ('Puerto Rico de Mogán, Gran Canaria', 'Puerto Rico de Mogán, Gran Canaria',
             'El restaurante de Antonio protege su almacén de bebidas fuera de horario.',
             'Antonio’s restaurant protects its drinks store outside opening hours.'),
            ('Playa Blanca, Lanzarote', 'Playa Blanca, Lanzarote',
             'La tienda de recuerdos de Nieves detecta un intento de acceso por la puerta trasera.',
             'Nieves’s souvenir shop detects an attempt to get in through the back door.'),
            ('Morro Jable, Fuerteventura', 'Morro Jable, Fuerteventura',
             'La panadería de Miguel confirma que su local sigue cerrado durante las vacaciones de agosto.',
             'Miguel’s bakery confirms that the premises stay closed during the August holidays.'),
            ('Valle Gran Rey, La Gomera', 'Valle Gran Rey, La Gomera',
             'La peluquería de Susana recibe un aviso mientras estaba de viaje y llama a la policía a tiempo.',
             'Susana’s hair salon gets an alert while she is away and she calls the police in time.'),
            ('Breña Alta, La Palma', 'Breña Alta, La Palma',
             'La ferretería de Jorge protege su almacén exterior, que no tiene cámaras de seguridad.',
             'Jorge’s hardware shop protects its outdoor store, which has no security cameras.'),
        ],
    },
    {
        'id': 'residencias', 'ico': 'casa',
        'nombre': ('Segundas residencias', 'Second homes'),
        'necesidad': ('Seguridad sin depender de internet contratado', 'Security without needing an internet contract'),
        'soluciones': ['solucion-hogar-y-negocio'],
        'historias': [
            ('Tijarafe, La Palma', 'Tijarafe, La Palma',
             'La familia Hernández protege su casa de verano sin internet contratado.',
             'The Hernández family protects their summer house, which has no internet contract.'),
            ('Vallehermoso, La Gomera', 'Vallehermoso, La Gomera',
             'Roberto recibe un aviso de apertura de ventana en su casa vacía entre semana.',
             'Roberto gets a window-opening alert from his empty house during the week.'),
            ('El Pinar, El Hierro', 'El Pinar, El Hierro',
             'Una pareja de jubilados protege su vivienda mientras pasan el invierno en la península.',
             'A retired couple protects their home while they spend the winter on the mainland.'),
            ('Teguise, Lanzarote', 'Teguise, Lanzarote',
             'El chalet de los Martín queda cubierto ante los cortes de luz frecuentes de la zona rural.',
             'The Martín family’s house stays covered despite the frequent power cuts in the rural area.'),
            ('Betancuria, Fuerteventura', 'Betancuria, Fuerteventura',
             'La casa rural de Elvira avisa a los propietarios si alguien entra fuera de las fechas de reserva.',
             'Elvira’s rural guesthouse alerts the owners if anyone enters outside the booking dates.'),
            ('Teror, Gran Canaria', 'Teror, Gran Canaria',
             'La segunda residencia de Carlos queda protegida pese a la falta de cobertura fija de wifi en el pueblo.',
             'Carlos’s second home stays protected despite the lack of fixed wifi coverage in the village.'),
        ],
    },
    {
        'id': 'publicidad', 'ico': 'megafono',
        'nombre': ('Agencias de publicidad y anunciantes', 'Advertising agencies and advertisers'),
        'necesidad': ('Medir la exposición real de una marca en vehículos', 'Measure a brand’s real exposure on vehicles'),
        'soluciones': ['solucion-publicidad-en-movimiento'],
        'historias': [
            ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife',
             'La agencia de Laura mide el alcance real de una campaña en vehículos de reparto.',
             'Laura’s agency measures the real reach of a campaign on delivery vehicles.'),
            ('Las Palmas de Gran Canaria', 'Las Palmas de Gran Canaria',
             'El anunciante Raúl compara la exposición de su marca en dos flotas distintas de tours.',
             'Advertiser Raúl compares his brand’s exposure across two different tour fleets.'),
            ('Arrecife, Lanzarote', 'Arrecife, Lanzarote',
             'La agencia de Diego usa el informe mensual para justificar la renovación de un contrato de patrocinio.',
             'Diego’s agency uses the monthly report to justify renewing a sponsorship contract.'),
            ('Corralejo, Fuerteventura', 'Corralejo, Fuerteventura',
             'La marca de ropa de Cristina mide cuántas zonas turísticas recorre su publicidad en buggies al mes.',
             'Cristina’s clothing brand measures how many tourist areas its buggy advertising covers each month.'),
            ('San Sebastián de La Gomera', 'San Sebastián de La Gomera',
             'La agencia de eventos de Pablo demuestra a un cliente el recorrido real de una furgoneta rotulada durante una feria.',
             'Pablo’s events agency shows a client the real route of a branded van during a trade fair.'),
            ('Santa Cruz de La Palma', 'Santa Cruz de La Palma',
             'El anunciante local Beatriz decide doblar su inversión tras ver el informe de exposición del primer trimestre.',
             'Local advertiser Beatriz decides to double her investment after seeing the first-quarter exposure report.'),
        ],
    },
    {
        'id': 'particulares', 'ico': 'llave',
        'nombre': ('Particulares con vehículo propio', 'Private vehicle owners'),
        'necesidad': ('Antirrobo y localización', 'Anti-theft and tracking'),
        'soluciones': ['solucion-vehiculo'],
        'historias': [
            ('Icod de los Vinos, Tenerife', 'Icod de los Vinos, Tenerife',
             'Jonathan recupera su coche tras dejarlo aparcado en el aeropuerto una semana entera.',
             'Jonathan gets his car back after leaving it parked at the airport for a whole week.'),
            ('Gáldar, Gran Canaria', 'Gáldar, Gran Canaria',
             'Nieves detecta un intento de robo de su coche familiar gracias al aviso de vibración.',
             'Nieves detects an attempt to steal the family car thanks to the vibration alert.'),
            ('Yaiza, Lanzarote', 'Yaiza, Lanzarote',
             'El estudiante Marcos localiza su moto tras un despiste al aparcarla fuera de su zona habitual.',
             'Student Marcos finds his motorbike after absent-mindedly parking it outside his usual area.'),
            ('La Oliva, Fuerteventura', 'La Oliva, Fuerteventura',
             'La joven pareja formada por los Ramos comparte un solo coche y siempre sabe dónde lo dejó el otro.',
             'The young Ramos couple share one car and always know where the other one left it.'),
            ('Hermigua, La Gomera', 'Hermigua, La Gomera',
             'El abuelo Antonio usa el GPS para tranquilidad de la familia cada vez que conduce solo largas distancias.',
             'Grandad Antonio uses the GPS to reassure the family whenever he drives long distances alone.'),
            ('Puntagorda, La Palma', 'Puntagorda, La Palma',
             'El vecino Rubén recupera su coche tras un intento de sustracción en plena calle.',
             'Local resident Rubén gets his car back after an attempted theft in the street.'),
        ],
    },
    {
        'id': 'mascotas', 'ico': 'huella',
        'nombre': ('Dueños de mascotas', 'Pet owners'),
        'necesidad': ('Localización si se escapan', 'Tracking if they run off'),
        'soluciones': ['solucion-mascotas'],
        'historias': [
            ('Realejo Alto, Tenerife', 'Realejo Alto, Tenerife',
             'La familia López encuentra a su gato tras dos días perdido, gracias al collar GPS.',
             'The López family find their cat after two days missing, thanks to the GPS collar.'),
            ('Arucas, Gran Canaria', 'Arucas, Gran Canaria',
             'El perro de campo de Ismael, acostumbrado a corretear libre, siempre vuelve localizado a tiempo.',
             'Ismael’s farm dog, used to roaming free, is always located and back in time.'),
            ('Puerto del Carmen, Lanzarote', 'Puerto del Carmen, Lanzarote',
             'Mercedes encuentra a su perro tras escaparse durante una tormenta.',
             'Mercedes finds her dog after it ran off during a storm.'),
            ('Gran Tarajal, Fuerteventura', 'Gran Tarajal, Fuerteventura',
             'La turista Laura localiza a su perro perdido durante una excursión por la isla.',
             'Tourist Laura locates her dog after losing it on a trip around the island.'),
            ('Agulo, La Gomera', 'Agulo, La Gomera',
             'Un refugio de animales, llevado por Cristina, usa GPS en los perros de acogida temporal para tranquilidad de las familias.',
             'An animal shelter run by Cristina fits GPS to dogs in temporary foster care to reassure the families.'),
            ('Barlovento, La Palma', 'Barlovento, La Palma',
             'El pastor Manuel controla su rebaño de cabras con GPS en los animales líderes del grupo.',
             'Shepherd Manuel keeps track of his goat herd with GPS on the lead animals.'),
        ],
    },
]

# ---------------------------------------------------------------- Historias de éxito
# Una lista por solución, en el mismo orden que SOLUCIONES.
HISTORIAS_EXITO = {
    'solucion-vehiculo': [
        ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife',
         'Manuel aparca su furgoneta camperizada en la calle. A las 4 de la madrugada, un aviso de movimiento le permite localizarla y avisar a la Guardia Civil antes de que llegara al puerto.',
         'Manuel parks his campervan on the street. At 4 in the morning a movement alert lets him locate it and call the Guardia Civil before it reaches the port.'),
        ('Las Palmas de Gran Canaria', 'Las Palmas de Gran Canaria',
         'A Marta le desaparece el coche de un parking. Lo localiza en 20 minutos gracias a la ubicación en tiempo real.',
         'Marta’s car disappears from a car park. She finds it in 20 minutes thanks to the real-time location.'),
        ('Santa Cruz de La Palma', 'Santa Cruz de La Palma',
         'Pedro usa su moto para repartir. Un aviso de movimiento a las 3 de la madrugada le avisa de que alguien la está tocando en su propia calle.',
         'Pedro uses his motorbike for deliveries. A movement alert at 3 in the morning tells him someone is tampering with it on his own street.'),
        ('Aeropuerto de Fuerteventura', 'Fuerteventura Airport',
         'Elena deja el coche una semana entera antes de un viaje. Comprueba desde el móvil que sigue en el mismo sitio, sin sorpresas a la vuelta.',
         'Elena leaves her car for a whole week while she travels. She checks on her phone that it is still in the same place: no surprises when she gets back.'),
        ('Arrecife, Lanzarote', 'Arrecife, Lanzarote',
         'Carlos, electricista, recupera su furgoneta de herramientas gracias al aviso de desprendimiento del dispositivo.',
         'Carlos, an electrician, gets his tool van back thanks to the device’s removal alert.'),
        ('Valverde, El Hierro', 'Valverde, El Hierro',
         'El coche familiar de Ana sufre un intento de robo frustrado en la calle — el aviso de vibración llega a tiempo.',
         'Ana’s family car is the target of a foiled theft attempt in the street: the vibration alert arrives in time.'),
    ],
    'solucion-mascotas': [
        ('El Paso, La Palma', 'El Paso, La Palma',
         'Cova, la perra de los Hernández, se escapa durante los fuegos artificiales de las fiestas. La encuentran en 10 minutos, no en una noche entera.',
         'Cova, the Hernández family’s dog, runs off during the fireworks at the local fiesta. They find her in 10 minutes, not after a whole night.'),
        ('Telde, Gran Canaria', 'Telde, Gran Canaria',
         'El gato de Lucía se escapa por una ventana abierta. Lo localiza tres calles más allá antes de que anochezca.',
         'Lucía’s cat escapes through an open window. She finds it three streets away before nightfall.'),
        ('San Bartolomé, Lanzarote', 'San Bartolomé, Lanzarote',
         'Un perro se escapa durante un paseo de una residencia canina. Lo localizan antes de que llegue a la carretera.',
         'A dog gets away during a walk from a dog boarding kennel. They locate it before it reaches the road.'),
        ('El Teide, Tenerife', 'Mount Teide, Tenerife',
         'Una pareja de senderistas pierde de vista a su perro en pleno parque nacional. El collar GPS los lleva directos a él.',
         'A couple of hikers lose sight of their dog in the middle of the national park. The GPS collar takes them straight to it.'),
        ('Valle Gran Rey, La Gomera', 'Valle Gran Rey, La Gomera',
         'Un cachorro recién adoptado se cuela por una valla el primer día en casa. La familia lo recupera en minutos.',
         'A newly adopted puppy squeezes through a fence on its first day at home. The family gets it back in minutes.'),
        ('Puerto del Rosario, Fuerteventura', 'Puerto del Rosario, Fuerteventura',
         'Un negocio de paseadores profesionales usa Canary GPS para tranquilizar a los dueños durante cada paseo.',
         'A professional dog-walking business uses Canary GPS to reassure owners during every walk.'),
    ],
    'solucion-flotas': [
        ('Costa Adeje, Tenerife', 'Costa Adeje, Tenerife',
         'Rosa gestiona 6 coches de alquiler turístico. Ya no hay sorpresas en la facturación de combustible ni devoluciones tardías sin avisar.',
         'Rosa runs 6 tourist rental cars. No more surprises on the fuel bill or unannounced late returns.'),
        ('Las Palmas de Gran Canaria', 'Las Palmas de Gran Canaria',
         'Una empresa de reparto de comida a domicilio controla tiempos de entrega reales, no estimados.',
         'A food delivery company tracks real delivery times, not estimates.'),
        ('Puerto del Carmen, Lanzarote', 'Puerto del Carmen, Lanzarote',
         'Una constructora con varias furgonetas de material sabe en todo momento dónde está cada una.',
         'A building firm with several material vans knows where each one is at all times.'),
        ('Corralejo, Fuerteventura', 'Corralejo, Fuerteventura',
         'Una autoescuela con 4 coches de prácticas verifica las rutas de examen de sus alumnos.',
         'A driving school with 4 practice cars checks its students’ test routes.'),
        ('Los Llanos de Aridane, La Palma', 'Los Llanos de Aridane, La Palma',
         'Una empresa de mudanzas ofrece a sus clientes la ubicación del camión en tiempo real.',
         'A removals company offers its customers the lorry’s real-time location.'),
        ('Frontera, El Hierro', 'Frontera, El Hierro',
         'Una cooperativa agrícola controla el uso de tractores y remolques fuera de horario.',
         'A farming cooperative monitors the use of tractors and trailers outside working hours.'),
    ],
    'solucion-publicidad-en-movimiento': [
        ('Tenerife', 'Tenerife',
         'Una bodega local rotula tres jeeps de una empresa de tours. Cada viernes recibe un informe de kilómetros y zonas de mayor tránsito.',
         'A local winery brands three jeeps belonging to a tour company. Every Friday it receives a report on kilometres and the busiest areas.'),
        ('Gran Canaria', 'Gran Canaria',
         'Una marca de ron canario patrocina furgonetas de reparto y mide su exposición en distintas zonas de la isla.',
         'A Canarian rum brand sponsors delivery vans and measures its exposure in different parts of the island.'),
        ('Lanzarote', 'Lanzarote',
         'Una bodega de vinos de La Geria rotula los coches de una autoescuela y ve cuántas horas circulan al mes.',
         'A winery from La Geria brands a driving school’s cars and sees how many hours they are on the road each month.'),
        ('Fuerteventura', 'Fuerteventura',
         'Una escuela de surf patrocina las bicis de reparto de una empresa de comida saludable.',
         'A surf school sponsors the delivery bikes of a healthy food company.'),
        ('La Palma', 'La Palma',
         'Una cervecera artesanal compara la exposición de sus jeeps patrocinados entre temporada alta y baja turística.',
         'A craft brewery compares the exposure of its sponsored jeeps between the high and low tourist seasons.'),
        ('Gran Canaria', 'Gran Canaria',
         'Un concesionario de motos usa el informe mensual para decidir si renueva el patrocinio de una empresa de rutas guiadas.',
         'A motorbike dealer uses the monthly report to decide whether to renew its sponsorship of a guided tour company.'),
    ],
    'solucion-hogar-y-negocio': [
        ('Polígono industrial, Gran Canaria', 'Industrial estate, Gran Canaria',
         'Un almacén sin electricidad fija recibe el aviso de apertura de puerta pese a un corte de luz.',
         'A warehouse without a fixed power supply gets the door-opening alert despite a power cut.'),
        ('Barlovento, La Palma', 'Barlovento, La Palma',
         'Un negocio familiar cierra en temporada baja; el GPS avisa de cualquier movimiento en la persiana.',
         'A family business closes in the low season; the GPS reports any movement of the shutter.'),
        ('Haría, Lanzarote', 'Haría, Lanzarote',
         'Una segunda residencia sin internet contratado queda protegida igualmente gracias a la conexión propia del dispositivo.',
         'A second home with no internet contract is still protected thanks to the device’s own connection.'),
        ('Obra en construcción, Fuerteventura', 'Building site, Fuerteventura',
         'Una caseta con herramientas avisa en cuanto alguien manipula la puerta.',
         'A tool hut sends an alert as soon as someone tampers with the door.'),
        ('Los Cristianos, Tenerife', 'Los Cristianos, Tenerife',
         'El propietario de un alquiler vacacional recibe un aviso si alguien entra fuera de las fechas de reserva.',
         'The owner of a holiday let gets an alert if anyone enters outside the booking dates.'),
        ('Comunidad de vecinos, El Hierro', 'Residents’ association, El Hierro',
         'Un trastero comunitario sin cámara queda cubierto con un aviso de apertura fuera de horario.',
         'A shared storeroom with no camera is covered by an alert if it is opened out of hours.'),
    ],
}

# ---------------------------------------------------------------- Afiliados
AFI_PASOS = [
    (('Te damos un código propio', 'We give you your own code'),
     ('Tu código identifica a cada cliente que traigas, automáticamente.',
      'Your code automatically identifies every customer you bring in.')),
    (('Tu cliente compra con descuento', 'Your customer buys at a discount'),
     ('Cualquiera que use tu código paga un 10% menos, tanto en el dispositivo como en la suscripción — un incentivo real para elegir tu enlace antes que la web pública.',
      'Anyone who uses your code pays 10% less on both the device and the subscription: a real incentive to choose your link over the public website.')),
    (('Cobras comisión mientras el cliente siga activo', 'You earn commission while the customer stays active'),
     ('No es una comisión única: la cobras cada mes que ese cliente mantenga su suscripción.',
      'It isn’t a one-off commission: you earn it every month that customer keeps their subscription.')),
]

AFI_NIVELES = [
    (('Afiliado', 'Affiliate'), '1-4', '10%'),
    (('Revendedor', 'Reseller'), '5-14', '15%'),
    (('Distribuidor', 'Distributor'), '15+', '20%'),
]

AFI_FAQ = [
    (('¿Tengo que comprar dispositivos para revender?', 'Do I have to buy devices to resell?'),
     ('No. No hay stock ni compra mínima — cada cliente compra directamente con tu código.',
      'No. There is no stock and no minimum purchase: each customer buys directly with your code.')),
    (('¿Cuánto dura la comisión?', 'How long does the commission last?'),
     ('Mientras el cliente que trajiste mantenga su suscripción activa.',
      'For as long as the customer you brought in keeps their subscription active.')),
    (('¿Puedo vender bajo mi propia marca?', 'Can I sell under my own brand?'),
     ('No — el programa funciona con código de afiliado sobre la marca Canary GPS, no como reventa con marca propia.',
      'No. The programme works with an affiliate code under the Canary GPS brand, not as white-label resale.')),
]

AFI_CANALES = [
    ('Redes sociales', 'Social media'),
    ('Negocio propio', 'My own business'),
    ('Boca a boca', 'Word of mouth'),
    ('Otro', 'Other'),
]
